[metadata]
team = "vega"
domain = "circulation"
module = "mod-feesfines"

[[sources]]
name = "accounts"
table = "accounts"

[[entityTypes]]
name = "accounts"
private = false
schema = "./ramls/accountdata.json"
permissions = ["accounts.collection.get"]
source = "accounts"
sort = ["id", "ASC"]
useRmbIndexStyle = true
# these were not populated
fieldExclusions = [
  "date_created",
  "date_updated",
  "metadata_created_by_username",
  "metadata_updated_by_username",
]

[[sources]]
name = "comments"
table = "comments"

[[entityTypes]]
name = "comment_requirements"
private = false
schema = "./ramls/commentdata.json"
permissions = ["comments.collection.get"]
source = "comments"
sort = ["id", "ASC"]
# these were not populated
fieldExclusions = [
  "metadata_created_by_username",
  "metadata_updated_by_username",
]
[entityTypes.fieldOverrides.metadata_created_date]
x-fqm-visibility = 'hidden-non-queryable'

[entityTypes.fieldOverrides.metadata_created_by_user_id]
x-fqm-visibility = 'hidden-non-queryable'

[entityTypes.fieldOverrides.metadata_updated_by_user_id]
x-fqm-visibility = 'hidden-non-queryable'

[[sources]]
name = "feefineactions"
table = "feefineactions"

[[entityTypes]]
name = "feefine_actions"
private = false
schema = "./ramls/feefineactiondata.json"
permissions = ["feefineactions.collection.get"]
source = "feefineactions"
sort = ["id", "ASC"]
useRmbIndexStyle = true

[[sources]]
name = "feefines"
table = "feefines"

[[entityTypes]]
name = "feefines"
private = false
schema = "./ramls/feefinedata.json"
permissions = ["feefines.collection.get"]
source = "feefines"
sort = ["id", "ASC"]
useRmbIndexStyle = true
# these were not populated
fieldExclusions = [
  "metadata_created_by_username",
  "metadata_updated_by_username",
]

[[sources]]
name = "lost_item_fee_policy"
table = "lost_item_fee_policy"

[[entityTypes]]
name = "lost_item_fee_policy"
private = false
schema = "./ramls/lost-item-fee-policy.json"
permissions = ["lost-item-fees-policies.collection.get"]
source = "lost_item_fee_policy"
sort = ["id", "ASC"]
useRmbIndexStyle = true
# these were not populated
fieldExclusions = [
  "metadata_created_by_username",
  "metadata_updated_by_username",
]

[entityTypes.fieldOverrides.charge_amount_item_amount]
x-fqm-visible-by-default = true

[entityTypes.fieldOverrides.description]
x-fqm-visible-by-default = true

[entityTypes.fieldOverrides.metadata_created_by_user_id]
x-fqm-joins-to-raw = [
  { targetId = 'bb058933-cd06-4539-bd3a-6f248ff98ee2', targetField = 'id', type = 'equality-cast-uuid', direction = 'left'}, # simple_user
  { targetId = 'f2615ea6-450b-425d-804d-6a495afd9308', targetField = 'id', type = 'equality-cast-uuid', direction = 'left'} # simple_FOLIO_user
]
x-fqm-visibility = 'hidden-non-queryable'

[entityTypes.fieldOverrides.metadata_updated_date]
x-fqm-visibility = 'hidden-non-queryable'

[entityTypes.fieldOverrides.metadata_updated_by_user_id]
x-fqm-joins-to-raw = [
  { targetId = 'bb058933-cd06-4539-bd3a-6f248ff98ee2', targetField = 'id', type = 'equality-cast-uuid', direction = 'left'}, # simple_user
  { targetId = 'f2615ea6-450b-425d-804d-6a495afd9308', targetField = 'id', type = 'equality-cast-uuid', direction = 'left'} # simple_FOLIO_user
]
x-fqm-visibility = 'hidden-non-queryable'

[entityTypes.fieldOverrides.patron_billed_after_aged_lost_interval_id]
x-fqm-visible-by-default = true

[entityTypes.fieldOverrides.patron_billed_after_recalled_item_aged_lost_duration]
x-fqm-visible-by-default = true

[entityTypes.fieldOverrides.returned_lost_item_processing_fee]
x-fqm-visible-by-default = true


[[sources]]
name = "manual_block_templates"
table = "manual_block_templates"

[[entityTypes]]
name = "manual_block_templates"
private = false
schema = "./ramls/manual-block-template.json"
permissions = ["manual-block-templates.collection.get"]
source = "manual_block_templates"
sort = ["id", "ASC"]
useRmbIndexStyle = true
# these were not populated
fieldExclusions = [
  "metadata_created_by_username",
  "metadata_updated_by_username",
]

[[sources]]
name = "manualblocks"
table = "manualblocks"

[[entityTypes]]
name = "manual_blocks"
private = false
schema = "./ramls/manualblockdata.json"
permissions = ["manualblocks.collection.get"]
source = "manualblocks"
sort = ["id", "ASC"]
useRmbIndexStyle = true
# these were not populated
fieldExclusions = [
  "metadata_created_by_username",
  "metadata_updated_by_username",
]

[entityTypes.fieldOverrides.id]
x-fqm-visibility = "hidden-non-queryable"

[entityTypes.fieldOverrides.user_id]
x-fqm-joins-to-raw = [
  { targetId = 'bb058933-cd06-4539-bd3a-6f248ff98ee2', targetField = 'id', type = 'equality-cast-uuid', direction = 'left'}, # simple_user
  { targetId = 'f2615ea6-450b-425d-804d-6a495afd9308', targetField = 'id', type = 'equality-cast-uuid', direction = 'left'} # simple_FOLIO_user
]

[entityTypes.fieldOverrides.metadata_created_date]
x-fqm-visibility = "hidden-non-queryable"

[entityTypes.fieldOverrides.metadata_created_by_user_id]
x-fqm-joins-to-raw = [
  { targetId = 'bb058933-cd06-4539-bd3a-6f248ff98ee2', targetField = 'id', type = 'equality-cast-uuid', direction = 'left'}, # simple_user
  { targetId = 'f2615ea6-450b-425d-804d-6a495afd9308', targetField = 'id', type = 'equality-cast-uuid', direction = 'left'} # simple_FOLIO_user
]
x-fqm-visibility = "hidden-non-queryable"

[entityTypes.fieldOverrides.metadata_updated_date]
x-fqm-visibility = "hidden-non-queryable"

[entityTypes.fieldOverrides.metadata_updated_by_user_id]
x-fqm-joins-to-raw = [
  { targetId = 'bb058933-cd06-4539-bd3a-6f248ff98ee2', targetField = 'id', type = 'equality-cast-uuid', direction = 'left'}, # simple_user
  { targetId = 'f2615ea6-450b-425d-804d-6a495afd9308', targetField = 'id', type = 'equality-cast-uuid', direction = 'left'} # simple_FOLIO_user
]
x-fqm-visibility = "hidden-non-queryable"

[[sources]]
name = "overdue_fine_policy"
table = "overdue_fine_policy"

[[entityTypes]]
name = "overdue_fine_policies"
private = false
schema = "./ramls/overdue-fine-policy.json"
permissions = ["overdue-fines-policies.collection.get"]
source = "overdue_fine_policy"
sort = ["id", "ASC"]
useRmbIndexStyle = true
# these were not populated
fieldExclusions = [
  "metadata_created_by_username",
  "metadata_updated_by_username",
]

[[sources]]
name = "owners"
table = "owners"

[[entityTypes]]
name = "owners"
private = false
schema = "./ramls/ownerdata.json"
permissions = ["owners.collection.get"]
source = "owners"
sort = ["id", "ASC"]
# these were not populated
fieldExclusions = [
  "metadata_created_by_username",
  "metadata_updated_by_username",
]

[[sources]]
name = "payments"
table = "payments"

[[entityTypes]]
name = "payments"
private = false
schema = "./ramls/paymentdata.json"
permissions = ["payments.collection.get"]
source = "payments"
sort = ["id", "ASC"]
# these were not populated
fieldExclusions = [
  "metadata_created_by_username",
  "metadata_updated_by_username",
]

[[sources]]
name = "refunds"
table = "refunds"

[[entityTypes]]
name = "refunds"
private = false
schema = "./ramls/refunddata.json"
permissions = ["refunds.collection.get"]
source = "refunds"
sort = ["id", "ASC"]
# these were not populated
fieldExclusions = [
  "metadata_created_by_username",
  "metadata_updated_by_username",
]

[[sources]]
name = "transfers"
table = "transfers"

[[entityTypes]]
name = "transfers"
private = false
schema = "./ramls/transferdata.json"
permissions = ["transfers.collection.get"]
source = "transfers"
sort = ["id", "ASC"]
# these were not populated
fieldExclusions = [
  "metadata_created_by_username",
  "metadata_updated_by_username",
]

[[sources]]
name = "waives"
table = "waives"

[[entityTypes]]
name = "waives"
private = false
schema = "./ramls/waivedata.json"
permissions = ["waives.collection.get"]
source = "waives"
sort = ["id", "ASC"]
# these were not populated
fieldExclusions = [
  "metadata_created_by_username",
  "metadata_updated_by_username",
]
